inference_config: "configs/inference/inference-v2.yaml"
motion_module:
  # - "models/Motion_Module/mm_sd_v15_v2.ckpt"
  - "/data1/wtanae/AnimateDiff/models/Motion_Module/mm_sd_v15_v2.ckpt"

# dreambooth_path: "models/DreamBooth_LoRA/realisticVisionV20_v20.safetensors"
dreambooth_path: "/data1/wtanae/AnimateDiff/models/DreamBooth_LoRA/realisticVisionV51_v20Novae.safetensors"
lora_model_path: ""

# seed:           [9620, 913, 6840, 1334]
steps:          25
guidance_scale: 7.5

filter_params:
  method: 'butterworth'
  n: 4
  d_s: 0.25
  d_t: 0.25

# filter_params:
#   method: 'gaussian'
#   d_s: 0.25
#   d_t: 0.25

prompt:
  - "realistic running tiger, tense atmosphere, fire, abstract background"
  # - "close up photo of a rabbit, forest, haze, halation, bloom, dramatic atmosphere, centred, rule of thirds, 200mm 1.4f macro shot"
  # - "A panda cooking in the kitchen"
  # - "A cat wearing sunglasses and working as a lifeguard at a pool."
  # - "A confused panda in calculus class"
  # - "A robot DJ is playing the turntable, in heavy raining futuristic tokyo rooftop cyberpunk night, sci-fi, fantasy"

n_prompt:
  - "(deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers:1.4), (deformed, distorted, disfigured:1.3), poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, amputation"
  # - ""
  # - ""
  # - ""
  # - ""

